import {
  Loader2,
  Calendar,
  CheckCircle2,
  XCircle,
  Mail,
  Lock,
  User,
  LogOut,
  Settings,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Search,
  Plus,
  Minus,
  Star,
  Heart,
  Share2,
  MoreHorizontal,
  MoreVertical,
  Trash2,
  Edit,
  Copy,
  Link as LinkIcon,
  ExternalLink,
  Eye,
  EyeOff,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: Calendar,
  spinner: Loader2,
  check: CheckCircle2,
  close: XCircle,
  mail: Mail,
  lock: Lock,
  user: User,
  logout: LogOut,
  settings: Settings,
  menu: Menu,
  x: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  search: Search,
  plus: Plus,
  minus: Minus,
  star: Star,
  heart: Heart,
  share: Share2,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  trash: Trash2,
  edit: Edit,
  copy: Copy,
  link: LinkIcon,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  calendar: Calendar,
}; 